# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ARimport', [dirname(__file__)])
        except ImportError:
            import _ARimport
            return _ARimport
        if fp is not None:
            try:
                _mod = imp.load_module('_ARimport', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ARimport = swig_import_helper()
    del swig_import_helper
else:
    import _ARimport
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class markerInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, markerInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, markerInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _ARimport.markerInfo_x_set
    __swig_getmethods__["x"] = _ARimport.markerInfo_x_get
    if _newclass:x = _swig_property(_ARimport.markerInfo_x_get, _ARimport.markerInfo_x_set)
    __swig_setmethods__["y"] = _ARimport.markerInfo_y_set
    __swig_getmethods__["y"] = _ARimport.markerInfo_y_get
    if _newclass:y = _swig_property(_ARimport.markerInfo_y_get, _ARimport.markerInfo_y_set)
    __swig_setmethods__["ID"] = _ARimport.markerInfo_ID_set
    __swig_getmethods__["ID"] = _ARimport.markerInfo_ID_get
    if _newclass:ID = _swig_property(_ARimport.markerInfo_ID_get, _ARimport.markerInfo_ID_set)
    def __init__(self): 
        this = _ARimport.new_markerInfo()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ARimport.delete_markerInfo
    __del__ = lambda self : None;
markerInfo_swigregister = _ARimport.markerInfo_swigregister
markerInfo_swigregister(markerInfo)

class ARimport(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ARimport, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ARimport, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _ARimport.new_ARimport()
        try: self.this.append(this)
        except: self.this = this
    def findMarkers(self, *args): return _ARimport.ARimport_findMarkers(self, *args)
    def getFoundMarker(self, *args): return _ARimport.ARimport_getFoundMarker(self, *args)
    def setShowOutput(self, *args): return _ARimport.ARimport_setShowOutput(self, *args)
    def setOutputFileName(self, *args): return _ARimport.ARimport_setOutputFileName(self, *args)
    __swig_destroy__ = _ARimport.delete_ARimport
    __del__ = lambda self : None;
ARimport_swigregister = _ARimport.ARimport_swigregister
ARimport_swigregister(ARimport)

# This file is compatible with both classic and new-style classes.


